# Adapted from:
# https://patriksvensson.se/posts/2020/03/creating-release-artifacts-with-github-actions

name: Publish
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v* '

jobs:
  name: Publish DockerHub image

  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: taylort7147/board-game-db
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

